### ISSUE TITLE
Make application installable on Linux

### ISSUE THREAD

**Issue by mgorfer** [JuergenFleiss/aTrain#1]
Thank you for this great tool!

Would it be possible to also support the installation via Linux?

After following the steps in _Installation for developers_ and installing some more dependencies (in addition to the ones listed in the requirements.txt), it runs fine on my Linux Laptop.
Even better would be to make it directly installable for Linux.

I understand, of course, that Linux users might be a minor target group for this project, and that you would rather not officially support that platform too.

(Best regards from the Wegener Center!)

**Comment by Juergen-J-F** [comment]
Thanks for testing it.  @ArminHaberl rewrote the code and I have now added instructions for debian installation in the wiki: https://github.com/BANDAS-Center/aTrain/wiki/Linux-Support-(in-progress)

Would be great, @mgorfer, if you could test the new version and the instructions on your system and add any missing dependencies you encounter. The new version also brings subtitle support. 

Ideally of course, we will get a flatpak or deb package in the future.

**Comment by spipau** [comment]
I just tried to install aTrain on Ubuntu Ubuntu 24.04.1 LTS but fail as [the link in the readme](https://business-analytics.uni-graz.at/en/research/atrain/download/) does not offer any debs to download and [installation instructions from here don't work](https://github.com/JuergenFleiss/aTrain/wiki/Linux-Support).

Please consider packing aTrain as a flatpak and offer it via [Flathub](https://flathub.org/). Thank you and have a wonderful day :slightly_smiling_face:

**Comment by JuergenFleiss** [comment]
> I just tried to install aTrain on Ubuntu Ubuntu 24.04.1 LTS but fail as [the link in the readme](https://business-analytics.uni-graz.at/en/research/atrain/download/) does not offer any debs to download and [installation instructions from here don't work](https://github.com/JuergenFleiss/aTrain/wiki/Linux-Support).
> 
> Please consider packing aTrain as a flatpak and offer it via [Flathub](https://flathub.org/). Thank you and have a wonderful day 🙂

Hi, no flatpak yet.

But, I could get v1.2 running under Ubuntu 24.04 again and have updated the wiki installation instructions and also build a deb package under 24.04 (from my experience, this might not run in other ubuntu and debian versions though, which is flatpak and snap are up there on my list).

Testing the deb package would be greatly appreciated.
https://share.uni-graz.at/?s=download&token=0def1a13-940a-4d11-be11-c9a04d2bf984

**Comment by spipau** [comment]
I downloaded the .deb file and double clicked on my Ubuntu 24.04.1 LTS to open it with the default Ubuntu Store. Installation was offered and succeeded. Transcribed one short mp3 and worked :partying_face: 

You are missing one ` in the introduction.

Thank you and greetings from TU Graz :wink:

**Comment by JuergenFleiss** [comment]
Debian package made available for download under https://business-analytics.uni-graz.at/en/research/atrain/download/
