### ISSUE TITLE
Default MKV from OBS Studio not recognized as input

### ISSUE THREAD

**Issue by JuergenFleiss** [JuergenFleiss/aTrain#11]
Currently the default output MKV from OBS Studio is not working as input. Workaround is to switch to another output format in the OBS output settings.

**Comment by alexgu2008** [comment]
You can also use "File" -> "Remux recodings" directly in OBS to change the format without changing output settings. This should work for aTrain.

**Comment by JuergenFleiss** [comment]
default MKV from OBS Studio will be accepted in the upcomping new version.
