### ISSUE TITLE
transcribe error

### ISSUE THREAD

**Issue by proactive-dev** [JuergenFleiss/aTrain#15]
@JuergenFleiss @ArminHaberl 
I faced this issue when running  aTrain.
WIndows 10 and python 3.11
![Untitled](https://github.com/JuergenFleiss/aTrain/assets/31694991/ce66dbfd-9d1d-4a27-a913-4d49e1154689)

**Comment by ArminHaberl** [comment]
@proactive-dev, thank you for submitting this issue.
The underlying [faster-whisper](https://github.com/SYSTRAN/faster-whisper) library we use for aTrain introduced some changes in their new version that apparently break our transcription pipeline. We will update aTrain to set a fixed version of faster-whisper to prevent this issue.

A quick fix for you right now is to downgrade the faster-whisper version manually. You can use this command to do so:
`pip install --force-reinstall faster-whisper==0.9`

We hope this can help you resolve your issue.

Best regards,
Armin and the aTrain Team

**Comment by proactive-dev** [comment]
Thanks. Resolved.
