### ISSUE TITLE
Speaker Recognition

### ISSUE THREAD

**Issue by cauenapier** [JuergenFleiss/aTrain#17]
It would be quite powerful if it was possible to label speakers and somehow train the system so it could remember and recognize the speakers by it's name.
What would it take to do it?

**Comment by JuergenFleiss** [comment]
Hi, while I can see the attraction of such a feature, it seems that there is currently no ready-made solution for this and thus implementing this lies outside the scope of what we aim to provide. 

 I'll close the issue, but feel free to open it again if you find a package that would allow this.
