### ISSUE TITLE
[Errno 2] No such file or directory (metadata.txt)

### ISSUE THREAD

**Issue by hirowa** [JuergenFleiss/aTrain#20]
Hi, I can't make it work, I get this error every time.
I've tried with .mp3/.mp4 without success.
I've tried different models without success.
I've tried running it in admin/normal without success.
I've tried reinstalling without success.

I see it's an error regarding the app not being able to find the "metadata" file, but when I go to that path, it does exist, so I don't know what to do, hope you can help me :)

----

The following error occured:
[Errno 2] No such file or directory: 'C:\\Users\\user\\Documents\\aTrain\\transcriptions\\2024-04-21 17-01-35 10k_ent_challenge_\\metadata.txt'

Traceback:
Traceback (most recent call last): File "aTrain\transcribe.py", line 11, in handle_transcription File "aTrain\archive.py", line 54, in read_metadataFileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Documents\\aTrain\\transcriptions\\2024-04-21 17-01-35 10k_ent_challenge_\\metadata.txt'

**Comment by JuergenFleiss** [comment]
Could you try deinstalling deleting the whole "C:\Users\user\Documents\aTrain\" Folder 

Could you run it with the following short audio file I use for testing, just to be sure its not something strange with the file: http://www.hoertexte-deutsch.at/mp3/hawry.mp3

**Comment by hirowa** [comment]
Hi, thanks for your reply.
I did reinstall it from zero.
It works with small audios (Like your sample), but longer audios (~30min) get that error about the metadata.txt...

**Comment by JuergenFleiss** [comment]
Thats strange. I only know this behavior from GPU with very old cards where longer files fail. If you are using GPU, could you switch to CPU?

Could you share your hardware setup?

**Comment by wenyuan-wu** [comment]
The same problem happened to me, and it was solved by removing the hashtag (#) from the file name.

**Comment by hirowa** [comment]
@wenyuan-wu Sounds interesting, I'll see if by changing the file name it works, thanks!
---
Update: OMG it worked! Thanks for the tip, the problem comes from using special characters in the file name. Just avoid them :)
