### ISSUE TITLE
Support for large-v3 model

### ISSUE THREAD

**Issue by Zahrun** [JuergenFleiss/aTrain#25]
Support large-v3 model

**Comment by JuergenFleiss** [comment]
Support is incoming; we are currently finalizing the new version with our new [atrain_core ](https://github.com/JuergenFleiss/atrain_core) backend, this will, among other things, bring support for large-v3 as well as distilled models. So look for the new release in the next weeks

**Comment by Zahrun** [comment]
Thank you for the prompt reply.
I will be using aTrain-core with the cli in the meantime.

**Comment by warenhaus** [comment]
any news, by chance?

**Comment by ArminHaberl** [comment]
Hi @warenhaus,

Thank you for reaching out! We're currently in the final stages of testing aTrain v1.2, which will include support for the large-v3 model. We're working hard to resolve the remaining bugs and aim to release the new version by the end of August.

Thank you for your patience and support!

Best regards,
Armin & the aTrain Team
