### ISSUE TITLE
Feature request: Support for large-v3-turbo model

### ISSUE THREAD

**Issue by nhan000** [JuergenFleiss/aTrain#35]
> the turbo model is an optimized version of large-v3 that offers faster transcription speed with a minimal degradation in accuracy.

[openai/whisper: Robust Speech Recognition via Large-Scale Weak Supervision](https://github.com/openai/whisper)

[large-v3-turbo model by jongwook · Pull Request #2361 · openai/whisper](https://github.com/openai/whisper/pull/2361/files)

Thanks a lot for making Whisper so easy to use!

**Comment by nhan000** [comment]
Would you also consider adding support for large-v3 as well?

**Comment by JuergenFleiss** [comment]
Done in v1.2; released on Microsoft Store.
