### ISSUE TITLE
The 'Base model' and "Small model' cannot be downloaded.

### ISSUE THREAD

**Issue by Rohit236343** [JuergenFleiss/aTrain#42]
Everytime I try to download either the base or the small model, this error message shows up. 

**The following error occured: 
The model folder has been modified and will be deleted automatically. Please download model 'base' again if you wish to use it.**

**### Show Traceback
Traceback (most recent call last): File "a Train\models.pyll, line 212, in try_to_download_model File "a line 75, in get_model File "a Train_core\load_resources.py", line 90, in assert_model_hash Assertion Error: The model folder has been modified and will be deleted automatically. Please download model 'base' again if you wish to use it.**

I am using Windows 11.

**Comment by mussaj** [comment]
Yea only the turbo model comes with works for me. Other models won't effectively transcribe anything. Something to note for next update. Thanks and appreciate the hard work from the team.

**Comment by Rohit236343** [comment]
> Yea only the turbo model comes with works for me. Other models won't effectively transcribe anything. Something to note for next update. Thanks and appreciate the hard work from the team.

The issue I am facing is relating to the very download of 'base' and 'small' models. They just won't download. The error, referred to in the OP, keeps popping up every time.

On the other hand, I have been able to download the tiny, medium, faster-distil-english models, and they work quite well, thanks to the developers.

**Comment by JuergenFleiss** [comment]
> Everytime I try to download either the base or the small model, this error message shows up.
> 
> **The following error occured: The model folder has been modified and will be deleted automatically. Please download model 'base' again if you wish to use it.**
> 
> **### Show Traceback Traceback (most recent call last): File "a Train\models.pyll, line 212, in try_to_download_model File "a line 75, in get_model File "a Train_core\load_resources.py", line 90, in assert_model_hash Assertion Error: The model folder has been modified and will be deleted automatically. Please download model 'base' again if you wish to use it.**
> 
> I am using Windows 11.

Hi, thanks for reporting the bug, I could successfully reproduce it and we will have a look. The error for those two models is a false positive for a check in case users manually somehow modify the downloaded models.

**Comment by JuergenFleiss** [comment]
> Yea only the turbo model comes with works for me. Other models won't effectively transcribe anything. Something to note for next update. Thanks and appreciate the hard work from the team.

Hi, could you give me some more info on your problems with the models besides turbo?

**Comment by mussaj** [comment]
Nevermind. I restarted my PC and it works now. Sorry for the confusion. The english-distill model works amazingly.

**Comment by Rohit236343** [comment]
> > Everytime I try to download either the base or the small model, this error message shows up.
> > **The following error occured: The model folder has been modified and will be deleted automatically. Please download model 'base' again if you wish to use it.**
> > **### Show Traceback Traceback (most recent call last): File "a Train\models.pyll, line 212, in try_to_download_model File "a line 75, in get_model File "a Train_core\load_resources.py", line 90, in assert_model_hash Assertion Error: The model folder has been modified and will be deleted automatically. Please download model 'base' again if you wish to use it.**
> > I am using Windows 11.
> 
> Hi, thanks for reporting the bug, I could successfully reproduce it and we will have a look. The error for those two models is a false positive for a check in case users manually somehow modify the downloaded models.

First of, thank you very much for developing such a good app.
And thank you for such a quick response. 

I have tried reinstalling the app, but the bug still persists, and the 'base' and 'small' models cannot be downloaded, due to the same error.
I'm on Version 1.2.0 of aTrain. I'm using Windows 11.
Hoping for a fix.
