### ISSUE TITLE
Feature request: Transcribe from audio source

### ISSUE THREAD

**Issue by Flavescent** [JuergenFleiss/aTrain#45]
Hi, thank you very much for this application. It is surprisingly difficult to find a LLM transcription sofware with a casual user-friendly Windows GUI.

I'd very much appreciate it if you could consider adding the option to transcribe from an audio source (such as a microphone) instead of from an audio file.  This would allow users to more easily use ATrain as a dictation tool.

Ideally, given enough GPU power, this would allow live transcription, but if that is not possible, asynchronous transcription would also be good to have.

For dictation purposes, it would also be easier to be able to copy the text output from a GUI window, instead of having to manually open the generated text file.

**Comment by JuergenFleiss** [comment]
Hi, currently we have no plans; but have a look at https://github.com/savbell/whisper-writer

Installation is a bit more manual though.
