### ISSUE TITLE
The result of transcription in Chinese are different between v2 and v3(v3 turbo)

### ISSUE THREAD

**Issue by happypig** [JuergenFleiss/aTrain#47]
Transcription with Chinese test file in #41 are totally in Traditional Chinese with whisper v2 eventually, however the results mixed with Traditional and Simplified Chinese with v3 and v3 turbo.

Is there a way to assign the result with either Traditional Chinese or Simplified Chinese but not a mix?

**Comment by JuergenFleiss** [comment]
Thats an issue of the whisper models themselves, with the solution being to pass an initial prompt to the model. 
See the discussion here: https://github.com/openai/whisper/discussions/277

We already have pull requests https://github.com/JuergenFleiss/aTrain/pull/37 and https://github.com/JuergenFleiss/atrain_core/pull/23 by @Bytestorm5 for implementing the initial prompt parameter, but are currently to busy bugfixing to review and merge it. Hope to get to it soon, hopefully together with the bugfix release for the freezing UI and tiny and small model download errors.

**Comment by JuergenFleiss** [comment]
Initial Prompt included in main and the upcoming v1.2.1 release (as new advanced setting).
Thanks again @Bytestorm5 for the pull request.

Usage as per https://github.com/openai/whisper/discussions/277#discussioncomment-3832154:
For example, by prompting in a certain style (i.e. --initial_prompt with a sentence that may have come before what's spoken in the audio), you can steer the model to transcribe [the same audio file](https://datasets-server.huggingface.co/assets/google/fleurs/--/cmn_hans_cn/train/0/audio/audio.wav) in either traditional or simplified Chinese, as well as to write with punctuations:

$ whisper --language Chinese --model large audio.wav
[00:00.000 --> 00:08.000] 如果他们使用航空的方式运输货物在某些航线上可能要花几天的时间才能卸货和通关
$ whisper --language Chinese --model large audio.wav --initial_prompt "以下是普通話的句子。"  # traditional
[00:00.000 --> 00:08.000] 如果他們使用航空的方式運輸貨物,在某些航線上可能要花幾天的時間才能卸貨和通關。
$ whisper --language Chinese --model large audio.wav --initial_prompt "以下是普通话的句子。"  # simplified
[00:00.000 --> 00:08.000] 如果他们使用航空的方式运输货物,在某些航线上可能要花几天的时间才能卸货和通关。

**Comment by happypig** [comment]
@JuergenFleiss Many thanks. Look forward to the upcoming v1.2.1 release.
