### ISSUE TITLE
PyInstaller error

### ISSUE THREAD

**Issue by stevevaius2015** [JuergenFleiss/aTrain#8]
I tried to generate exe via `PyInstall build.spec` but I received this error 

`858 INFO: PyInstaller: 6.1.0
859 INFO: Python: 3.10.11
868 INFO: Platform: Windows-10-10.0.19045-SP0
1121 INFO: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
1121 INFO: NumExpr defaulting to 8 threads.
3782 WARNING: The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
5108 WARNING: The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyInstaller\__main__.py", line 209, in <module>
    run()
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyInstaller\__main__.py", line 189, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyInstaller\building\build_main.py", line 1042, in main 
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyInstaller\building\build_main.py", line 982, in build 
    exec(code, spec_namespace)
    datas += copy_metadata('safetensors')
metadata
    dist = importlib_metadata.distribution(package_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\metadata\__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\metadata\__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for safetensors`

I can run `python -m aTrain start` and get app working but can not build executable by above method. What can be issues? 

pip list: 

- accelerate                0.24.1
- aiohttp                   3.8.4
- aiosignal                 1.3.1
- alembic                   1.12.1
- altair                    4.2.2
- altgraph                  0.17.4
- amqp                      5.1.1
- antlr4-python3-runtime    4.9.3
- anyio                     3.6.2
- appdirs                   1.4.4
- asteroid-filterbanks      0.4.0
- asttokens                 2.4.0
- async-timeout             4.0.2
- aTrain                    1.1.0       D:\xxx\Speech\SpeechGUI\Bandas\aTrain
- attrs                     23.1.0
- audioread                 3.0.1
- av                        10.0.0
- backcall                  0.2.0
- backoff                   2.2.1
- billiard                  4.1.0
- blinker                   1.6.2
- bottle                    0.12.25
- cachetools                5.3.0
- camelot-py                0.9.0
- celery                    5.3.1
- certifi                   2023.5.7
- cffi                      1.15.1
- chardet                   5.1.0
- charset-normalizer        3.1.0
- chromadb                  0.3.21
- click                     8.1.3
- click-didyoumean          0.3.0
- click-plugins             1.1.1
- click-repl                0.3.0
- clickhouse-connect        0.5.23
- clr-loader                0.2.6
- colorama                  0.4.6
- coloredlogs               15.0.1
- colorlog                  6.7.0
- colour                    0.1.5
- configparser              3.5.3
- contourpy                 1.1.0
- cryptography              41.0.1
- ctranslate2               3.21.0
- cycler                    0.11.0
- Cython                    0.29.36
- dataclasses-json          0.5.7
- datasets                  2.14.6
- decorator                 5.1.1
- deepgram-sdk              2.11.0
- dill                      0.3.7
- dnspython                 2.4.2
- docopt                    0.6.2
- docx                      0.2.4
- duckdb                    0.7.1
- einops                    0.7.0
- email-validator           2.1.0.post1
- entrypoints               0.4
- et-xmlfile                1.1.0
- exceptiongroup            1.1.2
- executing                 1.2.0
- fastapi                   0.95.1
- faster-whisper            0.9.0
- ffmpeg-python             0.2.0
- filelock                  3.12.0
- Flask                     2.3.2
- flaskwebgui               1.0.8
- flatbuffers               23.5.26
- fonttools                 4.42.1
- frozenlist                1.3.3
- fsspec                    2023.5.0
- future                    0.18.3
- gitdb                     4.0.10
- GitPython                 3.1.31
- glcontext                 2.4.0
- greenlet                  3.0.0
- h11                       0.14.0
- hnswlib                   0.7.0
- httpcore                  0.18.0
- httptools                 0.5.0
- httpx                     0.25.0
- huggingface-hub           0.15.1
- humanfriendly             10.0
- HyperPyYAML               1.2.2
- idna                      3.4
- imageio                   2.32.0
- importlib-metadata        6.6.0
- iniconfig                 2.0.0
- ipython                   8.15.0
- isosurfaces               0.1.0
- itsdangerous              2.1.2
- jedi                      0.19.0
- Jinja2                    3.1.2
- joblib                    1.2.0
- jsonschema                4.17.3
- julius                    0.2.7
- kiwisolver                1.4.5
- kombu                     5.3.1
- langchain                 0.0.154
- lazy_loader               0.3
- librosa                   0.10.1
- lightning                 2.1.1
- lightning-utilities       0.9.0
- llama-cpp-python          0.1.41
- llvmlite                  0.41.1
- lxml                      4.9.2
- lz4                       4.3.2
- Mako                      1.3.0
- ManimPango                0.4.3
- mapbox-earcut             1.0.1
- markdown-it-py            2.2.0
- MarkupSafe                2.1.2
- marshmallow               3.19.0
- marshmallow-enum          1.5.1
- matplotlib                3.7.2
- matplotlib-inline         0.1.6
- mdurl                     0.1.2
- moderngl                  5.8.2
- moderngl-window           2.4.4
- monotonic                 1.6
- mpmath                    1.3.0
- msgpack                   1.0.7
- multidict                 6.0.4
- multipledispatch          1.0.0
- multiprocess              0.70.15
- mypy-extensions           1.0.0
- networkx                  3.1
- nltk                      3.8.1
- numba                     0.58.1
- numexpr                   2.8.4
- numpy                     1.24.3
- omegaconf                 2.3.0
- onnxruntime               1.16.2
- openapi-schema-pydantic   1.2.4
- opencv-python             4.8.1.78
- openpyxl                  3.1.2
- optimum                   1.13.2
- optuna                    3.4.0
- orjson                    3.9.10
- packaging                 23.1
- pandas                    2.0.1
- parso                     0.8.3
- patsy                     0.5.3
- pdfminer.six              20221105
- pefile                    2023.2.7
- pickleshare               0.7.5
- Pillow                    9.5.0
- pip                       23.3.1
- platformdirs              3.11.0
- playwright                1.39.0
- plotly                    5.15.0
- plotly-express            0.4.1
- pluggy                    1.2.0
- pmdarima                  2.0.3
- pooch                     1.8.0
- posthog                   3.0.1
- primePy                   1.3
- prompt-toolkit            3.0.38
- protobuf                  3.20.2
- proxy-tools               0.1.0
- psutil                    5.9.6
- pure-eval                 0.2.2
- pyannote.audio            3.0.0
- pyannote.core             5.0.0
- pyannote.database         5.0.1
- pyannote.metrics          3.2.1
- pyannote.pipeline         3.0.1
- pyarrow                   12.0.0
- PyAudio                   0.2.14
- pycparser                 2.21
- pydantic                  1.10.7
- pydeck                    0.8.1b0
- pydub                     0.25.1
- pyee                      11.0.1
- pyglet                    2.0.9
- Pygments                  2.15.1
- pygpt4all                 1.0.1
- pygptj                    1.0.10
- pyinstaller               6.1.0
- pyinstaller-hooks-contrib 2023.10
- pyllamacpp                1.0.6
- Pympler                   1.0.1
- PyOpenGL                  3.1.7
- pyparsing                 3.0.9
- PyPDF2                    3.0.1
- pyperclip                 1.8.2
- pyreadline3               3.4.1
- pyrr                      0.10.3
- pyrsistent                0.19.3
- PySimpleGUI               4.60.5
- pytest                    7.4.0
- pytest-base-url           2.0.0
- pytest-playwright         0.4.3
- python-dateutil           2.8.2
- python-dotenv             1.0.0
- python-multipart          0.0.6
- python-slugify            8.0.1
- pythonnet                 3.0.3
- pytorch-lightning         2.1.1
- pytorch-metric-learning   2.3.0
- pytz                      2023.3
- pytz-deprecation-shim     0.1.0.post0
- pywebview                 4.2.2
- pywin32                   306
- pywin32-ctypes            0.2.2
- PyYAML                    6.0
- regex                     2023.5.5
- requests                  2.31.0
- rich                      13.3.5
- ruamel.yaml               0.18.5
- ruamel.yaml.clib          0.2.8
- scikit-image              0.22.0
- scikit-learn              1.2.2
- scipy                     1.10.1
- screeninfo                0.8.1
- semver                    3.0.2
- sentence-transformers     2.2.2
- sentencepiece             0.1.99
- shellingham               1.5.4
- show-in-file-manager      1.1.4
- six                       1.16.0
- skia-pathops              0.8.0
- smmap                     5.0.0
- sniffio                   1.3.0
- sortedcontainers          2.4.0
- soundfile                 0.12.1
- soxr                      0.3.7
- speechbrain               0.5.15
- SQLAlchemy                2.0.12
- stack-data                0.6.2
- starlette                 0.26.1
- statsmodels               0.14.0
- streamlit                 1.22.0
- streamlit-ace             0.1.1
- svgelements               1.9.6
- sympy                     1.12
- tabulate                  0.9.0
- tenacity                  8.2.2
- tensorboardX              2.6.2.2
- text-unidecode            1.3
- threadpoolctl             3.1.0
- tifffile                  2023.9.26
- tokenizers                0.13.3
- toml                      0.10.2
- tomli                     2.0.1
- toolz                     0.12.0
- torch                     2.0.0+cu118
- torch-audiomentations     0.11.0
- torch-pitch-shift         1.2.4
- torchaudio                2.0.1+cu118
- torchmetrics              1.2.0
- torchvision               0.16.0
- tornado                   6.3.1
- tqdm                      4.65.0
- traitlets                 5.9.0
- transformers              4.28.1
- typer                     0.9.0
- typing_extensions         4.6.3
- typing-inspect            0.8.0
- tzdata                    2023.3
- tzlocal                   4.3
- ujson                     5.8.0
- urllib3                   1.26.18
- uvicorn                   0.22.0
- validators                0.20.0
- vine                      5.0.0
- wakepy                    0.7.2
- watchdog                  3.0.0
- watchfiles                0.19.0
- wcwidth                   0.2.6
- websockets                10.4
- Werkzeug                  3.0.1
- whisper-ctranslate2       0.1.7
- xxhash                    3.4.1
- yarl                      1.9.2
- zipp                      3.15.0
- zstandard                 0.21.0

**Comment by JuergenFleiss** [comment]
closed as we rewrote the whole thing
