### ISSUE TITLE
aTrain from windows store

### ISSUE THREAD

**Issue by dubr1k** [JuergenFleiss/aTrain#9]
Hello!
Could you please upload the old version of the aTrain application from the Windows Store to a file-sharing service? The new version keeps crashing. I suspect it's somehow related to the speaker diarization feature.

**Comment by jkpathan** [comment]
Same here. Keeps crashing on windows

**Comment by JuergenFleiss** [comment]
Are you getting any error messages?

**Comment by jkpathan** [comment]
I feed the app a 40min mp3 audio file. It seems to convert it to wav format first and then just turns off. No error messages displayed.

I find the wav file in the archives list and click open to find the file in the folder. There is also a metadata file. 

Is there a logs folder I should look for?
